### ISSUE TITLE
Allow renaming of field ID

### ISSUE THREAD

**Issue by didaktio** [contentful/contentful-management.js#1168]
contentful-migration supports field ID renaming with `newId()`.  I'm wondering why contentful-management doesn't? This is causing a real headache in an enterprise account with 40+ environments, where the batching flow of 'contentful-migration-type' scripts doesn't allow for super fine-grain ops.

**Comment by Spring3** [comment]
Hello @didaktio 
Sorry for a delay. For future I would like to kindly suggest to open a ticket on support in order to get the response faster.

You are able to change the id of the field if you pass the `newId` property.

Example:
```json
{
    "name": "Test-ct",
    "fields": [{
        "id": "title",
        "name": "Title",
        "required": false,
        "localized": false,
        "type": "Symbol"
    }, {
        "id": "name",         // current id of this field
        "name": "Name",
        "newId": "appName",   // here
        "required": false,
        "localized": false,
        "type": "Symbol"
    }]
}
```

I will open a ticket to one of the teams to update the documentation

**Comment by Spring3** [comment]
I will close this issue, but feel free to re-open it later
