### ISSUE TITLE
relationshipType not supported

### ISSUE THREAD

**Issue by danielcasadosoto** [contentful/contentful-management.js#1202]
Everytime we update a field in our Compose: Page, users are prompted to enable composite relationship in the Compose App because the content field loses this property, but unfortunately its edition is not supported in this project.

After some research, it seems that this property has support in [contentful-cli](https://github.com/contentful/contentful-cli).

Are there any plans to include it or a decent workaround?

**Comment by dustinbrownman** [comment]
Note, the experimental version hasn't been updated in about 6 months so there are some APIs that don't work, like `defaultValue` when creating a field.

**Comment by Spring3** [comment]
Hey @dustinbrownman @danielcasadosoto. It's been a while since you asked this question, but I wanted to let you know anyway that composite relationships are considered a deprecated feature. Please consider migrating to Aggregates instead.

<img width="759" alt="Screenshot 2022-08-04 at 15 07 13" src="https://user-images.githubusercontent.com/4171202/182854739-43e37f43-2e18-4bf8-9ade-c689392af984.png">

You can read more about it here https://www.contentful.com/developers/docs/compose/page-types/#page-components
