### ISSUE TITLE
Validation error when linking entries

### ISSUE THREAD

**Issue by jdwillemse** [contentful/contentful-management.js#131]
I'm creating a new entry and then linking it to an existent entry. All this works fine up until I try publishing the updated entry. I get this error:

```
UnresolvedLinks: {
  "status": 422,
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "notResolvable",
        "link": {
          "type": "Link",
          "linkType": "Entry",
          "id": "5MAs2AACkgQsWagS0uYWI4"
        },
        "path": [
          "fields",
          "recommendations",
          "en-GB",
          5
        ]
      }
    ]
  },
``` 

My code looks like this 
```
  return getWorkspace
    .then((space) => space.getEntry(userId))
    .then((entry) => {
      entry.fields.recommendations[LOCALE].push(newRecommendationLink);
      return entry.update();
    })
    .then((entry) => entry.publish())
```
If I leave the `.publish()` step off there is no error.

**Comment by axe312ger** [comment]
Freshly created entries might take a few seconds to propagate through our system. If `newRecommendationLink ` just got created before you link it in your recommendations field, you may need to wait a moment.

Can you try to add a delay of about 2-3 seconds before u run `entry.publish()`? This should fix your problem :)


Greetings,
Benedikt

**Comment by jdwillemse** [comment]
That sounds like a truly terrible solution! Shouldn't you instead only resolve a promise once the result is known?

**Comment by jdwillemse** [comment]
A timeout did solve the problem

**Comment by axe312ger** [comment]
I am sorry, but this is the way the API is working. Of course, we (as JS SDK) are waiting for the request to be finished and resolve with the result we get from the API.

Also, I handed over your feedback to the product team. We will work on this and fix it, but I can not give any timeline yet.

Another option would be retrying with minimal delay the publish as long it returns a status 422. Since the time for new entries to propagate in our system is depending on many factors, you may end up with almost no delay for the end user and bigger delays in case the system needs a few more milliseconds to know about your new entry.

**Comment by axe312ger** [comment]
How did you timeout and how is it different to my suggested delay? :)

**Comment by axe312ger** [comment]
Closing since no feedback since 14 days
