### ISSUE TITLE
Getting 404 error getEnvironments method

### ISSUE THREAD

**Issue by itsppal02** [contentful/contentful-management.js#1838]
I am trying to access environments of space but getting error 
![image](https://github.com/contentful/contentful-management.js/assets/58366406/a3751cd2-0a29-496e-b93a-20472e67a199)
I already allowed all enviourments in API token but still getting error
![image](https://github.com/contentful/contentful-management.js/assets/58366406/d26eaa33-9dcc-4e11-967d-48fade4b243a)
This are associated Environments of my space
![image](https://github.com/contentful/contentful-management.js/assets/58366406/7854cc60-b41f-4d99-8090-7fa0d1a0a53d)
This is code 
```
import * as contentful from 'contentful-management';
const client = contentful.createClient({
    accessToken: TOKEN,
    host: 'cdn.contentful.com',
});
const main = async () => {
    const space = await client.getSpace(SPACE_ID);
    const env = await space.getEnvironments();
}
main();

Please help me on that error

**Comment by rahulaakaram13** [comment]
+1

**Comment by RobertMrowiec** [comment]
+1

**Comment by RobertMrowiec** [comment]
@itsppal02 @rahulaakaram13 are you sure, you've used TOKEN from CMA Personal Tokens, not just Contentful Access Token? 

![image](https://github.com/contentful/contentful-management.js/assets/25043084/8218b1bf-7f51-4b38-88d4-a8a3a6baad23)

**Comment by Vinz93** [comment]
@itsppal02 if you need to fetch the environments you should use the **contentful-management API (CMA)** with your **cma-token** not the API key used for the Delivery API, please make sure that your token is not compromised since its bound to your account, with the same permissions across your spaces and organizations.

Similar question for reference #1839

I'm closing this ticket for now, but feel free to reach out again
if you have more questions.

Best
Vincenzo
