### ISSUE TITLE
Space.getEntries() will be removed in future major versions.  Please migrate your code to use Environment.getEntries():

### ISSUE THREAD

**Issue by folamy** [contentful/contentful-management.js#198]

**Comment by folamy** [comment]
Please how can i solve this

**Comment by phoebeschmidt** [comment]
Hi @folamy,

Since we added the feature for space environments, this warning was added to encourage you to use the api on the Environments entity instead of space. 

For example:
```
const contentful = require('contentful-management')

const client = contentful.createClient({
  accessToken: '<content_management_api_key>'
})

client.getSpace('<space_id>')
.then((space) => space.getEnvironment('<environment_id>'))
.then((environment) => environment.getEntries())
.then((response) => console.log(response.items))
.catch(console.error)
```

For now, when requesting all entries from the space, you are implicitly requesting entries from the default `master` environment. To make the warning go away, you need to explicitly request your environment, and then the entries. More about space environments can be found here: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/environments

https://www.contentful.com/developers/docs/concepts/multiple-environments/

Hope this helps!
