### ISSUE TITLE
basic npm install causes errors.

### ISSUE THREAD

**Issue by jamieowen** [contentful/contentful-management.js#49]
Hi,

Great work on contentful guys!

I'm getting a real basic error from the get go using the current version 1.0.2 of the contentful-management api.  I'm a bit strapped for time as well so can't be digging too much - and noticed that this version has also just been published... so wondering if you could help...

I've installed with npm install contentful-management

But as soon as i require( 'contentful-management' ) in a basic express server app, 
I get 
```
Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
```

It seems that no require statements inside contentful-management are resolving as if i install the babel-register module to my own package it just results in 
```
Error: Cannot find module './lib/contentful-management'
    at Function.Module._resolveFilename (module.js:325:15)
```

I don't get any issue with the standard Contentful Delivery SDK.. 

Cheers,

Jamie

**Comment by jamieowen** [comment]
Hey, 

So i think i've got to the bottom of it..

In the most recent version of contentful & contentful-management they are listing different dependencies in the package.json.

contentful:
```
  "dependencies": {
    "babel-runtime": "^6.3.19",
    "contentful-sdk-core": "^2.2.1",
    "json-stringify-safe": "^5.0.1",
    "lodash": "^4.2.0"
  },
```

contentful-management:
```
  "dependencies": {
    "contentful-sdk-core": "^2.2.4"
  },
```

If i add the missing three packages from contentful - contentful management starts working..

Hopefully this just a small mistake with the latest version increase?

**Comment by trodrigues** [comment]
Hello Jamie,

yes, we just released a new version of contentful-management that was heavily rewritten.

You are quite right that the problem here is the missing babel-runtime and lodash dependencies. I've just added it and pushed a new version which should be built and published soon.

I'm a bit concerned with we didn't catch this in our tests as we've even been testing it across multiple Node.js versions, so I'll have to investigate this a bit.

Could you maybe tell me which node and npm versions you are using?

Apologies for the issue and thanks for letting us know.

**Comment by jamieowen** [comment]
No worries.

I had tried on two versions of node - 4.2. something, and then I updated to 4.4.5 to see if that was the cause - Both had the same issue until I added the missing deps.  Npm version 2.15.5

Cheers,

Jamie

**Comment by trodrigues** [comment]
Right, the issue here was possibly the npm version. npm 3 introduced a change where dependencies are deduplicated, even dependencies of dependencies. Because the contentful-sdk-core package has those missing dependencies, this was never an issue with npm 3.

I should've remembered there's still a lot of people using npm 2 and tested this using npm 2, so I'll make sure we don't forget about npm 2 users in the future. Apologies for the issue.

**Comment by Flood** [comment]
Same issue with latest contentful version on npm.

**Comment by Khaledgarbaya** [comment]
@Flood Hi there what's the npm version you have ?

**Comment by Flood** [comment]
I have version 3.10.3
