### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by pvgn** [contentful/contentful-management.js#507]
It would be great to have [Deno](https://deno.land/) support.

I use this API to run some utilities through multiple projects, including an [Alfred](https://www.alfredapp.com/) workflow to have access to everything very quickly, and I would like to share that with others.

However, it's far from ideal to do that at the moment.
As one needs to `npm` (or `yarn`) `install` and have the same node_modules folder duplicated in one's system, plus in the cloud, like Dropbox syncing. Or `npm` (or `yarn`) `install` globally and [setup global folders](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders). And repeat that after a system update.
Not great for me neither for my users.

It would be more convenient, and secure, to just
`deno run --allow-net=api.contentful.com https://github.com/me/cf-utils/my-script.ts ...`

I guess it could be done by checking the Deno environment, and replacing Axios with a fetch-based tool in that case.
Is it something planned on your end?

**Comment by suevalov** [comment]
Thanks for bringing this up @pvgn 

Unfortunately we don't plan Deno support at the moment since it will require quite big rewrite and migration from `axios` as you've mentioned.

As a workaround I'd suggest using our CMA endpoints directly without using this client and use only types from this library for a better developer experince.
