### ISSUE TITLE
Contentful management is giving typescript error when running dev server

### ISSUE THREAD

**Issue by dalfriedrice** [contentful/contentful-management.js#513]
contentful-management/dist/typings/create-space-api.d.ts:832:33 - error TS2304: Cannot find name 'Omit'
contentful-management/dist/typings/create-organization-api.d.ts:149:48 - error TS2304: Cannot find name 'Omit'.

these are the errors i am getting while trying to run my dev server

It is written in the documentation that it supports typescript typings

**Comment by suevalov** [comment]
Hi @dalfriedrice, thanks for asking the question. 

It sounds to me that you're using a quite old Typescript version. `Omit` helper was introduced in typescript@3.5 (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html) and available since then.

Could you please verify the version and upgrade to the latest 3.x version if possible?

**Comment by dalfriedrice** [comment]
@suevalov Hey, thanks for the info, I forgot to reply back
Yeah I upgraded the TS version and it worked.. :)
