### ISSUE TITLE
"unPublish" specified on contentful.github.io is camelCase

### ISSUE THREAD

**Issue by AndrewBresee** [contentful/contentful-management.js#90]
https://contentful.github.io/contentful-management.js/contentful-management/1.3.0/typedef/index.html#static-typedef-ContentfulManagement

"unPublish" is camelCased in this documentation, but is not in code. Because 'un' is a prefix and not a word, the documentation should follow the code and not be camelCased ('unpublish').

**Comment by Khaledgarbaya** [comment]
Thanks @AndrewBresee will fix this asap

**Comment by axe312ger** [comment]
Hey Andrew,

that was already fixed in a24a4dca8fc6dfedaf4436158531301141c9c110 two months ago as u can see here https://contentful.github.io/contentful-management.js/contentful-management/3.3.4/typedef/index.html#static-typedef-ContentfulManagement

@AndrewBresee How did you end up in the old reference docs? Was this by accident or on purpose?

Best,
Benedikt
